import React from 'react'
import { Metadata } from 'next';
import Login from './login';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const page = () => {
  return (
   <Login/>
  )
}

export default page