import React from 'react'
import type { Metadata } from "next";
import Signup from './signup';
export const metadata: Metadata = {
    title: "Signup",
    description: "Generated by create next app",
  };
const page = () => {
  return (
    <Signup/>
  )
}

export default page